spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=student
spring.rabbitmq.password=student
stackapp.rabbitmq.queue=stackapp.queue1
stackapp.rabbitmq.exchange=stackapp.direct
stackapp.rabbitmq.routingkey=stackapp.routingkey
stackapp.rabbitmq.request.routingkey=stackapp.routingkey1
stackapp.rabbitmq.response.queue=stackapp.queue
stackapp.rabbitmq.response.routingkey=stackapp.routingkey
